name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install pnpm
          uses: pnpm/action-setup@v2
          with:
            version: 8.10.5
        
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.2
          with:
            node-version: 20.x
        
        - run: pnpm install --frozen-lockfile
        - run: pnpm run ci
        
